import React from "react"

import Layout from "../components/layout"
import SEO from "../components/seo"
import BacklogLogo from "../images/backlog_logo.png"

const BacklogPrivacyPolicy = () => (
  <Layout>
    <SEO title="Backlog : Privacy Policy" />
    <h2>Backlog Privacy Policy</h2>
    <img
              src={BacklogLogo}
              alt="Backlog logo"
              
              style={{ height: "200px", width: "200px" }}
            />
    <p>Nikhil Asrani built the Backlog app as an Open Source app. This SERVICE is provided by Nikhil Asrani at no cost and is intended for use as is.
<br/>
The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Thinder unless otherwise defined in this Privacy Policy.
<br/><br/>
<b>Information Collection and Use</b>
<br/>
Absolutely no Information Collection.
<br/><br/>
<b>Log Data</b>
<br/>
Absolutely no Data Logging.
<br/><br/>
<b>Links to Other Sites</b>
<br/>
This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by me. Therefore, I strongly advise you to review the Privacy Policy of these websites. I have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
<br/><br/>
<b>Changes to This Privacy Policy</b>
<br/>
I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.
<br/><br/>
<b>Contact Us</b>
<br/>
If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me.
<br/><br/>
This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator
</p>
  </Layout>
)

export default BacklogPrivacyPolicy


/*Privacy Policy
XerXes built the Get Off Your Phone app as an Open Source app. This SERVICE is provided by XerXes at no cost and is intended for use as is.

The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Get Off Your Phone unless otherwise defined in this Privacy Policy.

Information Collection and Use

Absolutely no information collection.

Log Data

Absolutely no data Logging.

Links to Other Sites

This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by me. Therefore, I strongly advise you to review the Privacy Policy of these websites. I have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

Changes to This Privacy Policy

I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.

Contact Us

If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me.

This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator


*/